### ISSUE TITLE
Specifying the full path of a web_accessible_resources resource throws "Unable to get file name for unknown file"

### ISSUE THREAD

**Issue by tgayle** [crxjs/rollup-plugin-chrome-extension#351]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

When specifying `resources` in `web_accessible_resources` by full path, `vite` and `vite build` fail with `Unable to get file name for unknown file "index.html"`. This does not fail and the file is successfully copied if the path contains a glob (`public/*`, etc).

Logs and repro below, but the particular failing line traces back to [plugin-manifest.ts:240](https://github.com/crxjs/rollup-plugin-chrome-extension/blob/main/packages/vite-plugin/src/node/plugin-manifest.ts#L240), I'm guessing because the file/asset isn't copied until [afterwards](https://github.com/crxjs/rollup-plugin-chrome-extension/blob/main/packages/vite-plugin/src/node/plugin-manifest.ts#L275).

### Reproduction

https://github.com/tgayle/web-accessible-resources-crxjs-bug

### Logs

```shell
[crx] error from file writer:
Error: Plugin error - Unable to get file name for unknown file "index.html".
    at error (/home/travis/web-accessible-crxjs-warn/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Object.FileEmitter.getFileName (/home/travis/web-accessible-crxjs-warn/node_modules/rollup/dist/shared/rollup.js:15589:24)
    at /home/travis/web-accessible-crxjs-warn/node_modules/rollup-plugin-chrome-extension/dist/index.cjs:3148:127
    at Array.map (<anonymous>)
    at /home/travis/web-accessible-crxjs-warn/node_modules/rollup-plugin-chrome-extension/dist/index.cjs:3148:32
    at Array.map (<anonymous>)
    at Object.generateBundle (/home/travis/web-accessible-crxjs-warn/node_modules/rollup-plugin-chrome-extension/dist/index.cjs:3147:82)
    at /home/travis/web-accessible-crxjs-warn/node_modules/rollup/dist/shared/rollup.js:22834:37
```

### System Info

```shell
System:
    OS: Linux 5.16 undefined
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 27.72 GB / 62.60 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 17.6.0 - ~/.nvm/versions/node/v17.6.0/bin/node
    npm: 8.5.1 - ~/.nvm/versions/node/v17.6.0/bin/npm
  Browsers:
    Chromium: 100.0.4896.127
    Firefox: 99.0.1
  npmPackages:
    rollup-plugin-chrome-extension: ^4.0.1-25 => 4.0.1-25 
    vite: ^2.9.7 => 2.9.7
```

### Severity

annoyance

**Comment by jacksteamdev** [comment]
@tgayle Thanks for taking the time to put together this excellent issue! This is certainly a bug!

The popup page and the web-accessible resource are the same `index.html` in your example. When the manifest plugin emits the resources afterward, it checks the explicit and globbed files against files in the output bundle. Since `index.html` already exists as the popup, it doesn't emit it again. That's why it works as a glob.

The offending code throws b/c the manifest plugin does not emit any resources before it looks up the file names. I'm removing this code since it doesn't do anything productive.

**Comment by jacksteamdev** [comment]
@tgayle This bugfix landed on NPM in `@crxjs/vite-plugin@1.0.2`. Please reopen this issue if you have any problems!

If you haven't migrated from RPCE to the new package name, I've posted instructions + codemod here: https://dev.to/jacksteamdev/rpce-is-moving-to-crxjsvite-plugin-2lmi
